---
title: "Du cercle trigonemetrique au calcul de l'aire d'un cercle"
author: "Goldentz Grahamz"
date: '2021-02-27'
categories: []
disable_jquery: no
featured: no
image:
  caption: 
  focal_point: ''
  preview_only: no
lastmod: '2020-07-27T20:45:57-07:00'
math: yes
projects: []
subtitle: ''
summary: 'Un cercle trigonemetrique'
tags:
- rmarkdown
- rshiny
- app
authors: []
output:
  blogdown::html_page:
    toc: false
runtime: shiny
---
<iframe width="800" height="420"
  src="https://quentin-gollentz.shinyapps.io/cercleTrigonemetrique/?_ga=2.244401350.2109755109.1614429842-1989212960.1613151693">
</iframe>

Cherchons l'aire du quart de cercle représenté par le triangle vert et la zone rouge.  
    
On peut faire remarquer que :  
$x^{2} + y^{2} = R$  
      
Il s'en suit que :  
$y = \sqrt{R^{2}-x^{2}}$  

L'aire du quart de cercle est donc donner par l'intégrale suivante :  
$I = \left(\int_{0}^{R}  \sqrt{R^{2}-x^{2}} \; dx\right)$  
  
Posons le changement de variable suivant :  
$x=R . sin(\theta)$  
  
Il s'en suit que :  
$\frac{\partial x}{\partial \theta}=R.cos(\theta)$ en se rappelant que $sin(u)'=u'cos(u)$  
  
On note donc :   
$\partial x=R.cos(\theta).\partial  \theta$  
  
Reste à calucler les nouvelles bornes :  
$sin(\theta)=\frac{x}{R}$  
      
Or lorsque $x=0$ le sinus d'un angle $\theta \in [0,\frac{\pi}{2}]$  tel que $sin(\theta)=0$ est donné par $\theta=0$  
Or lorsque $x=R$ le sinus d'un angle $\theta \in [0,\frac{\pi}{2}]$  tel que $sin(\theta)=1$ est donné par $\theta=\frac{\pi}{2}$  
  
On peut donc récrire l'intégrale précédente :  
$I = \left(\int_{0}^{\frac{\pi}{2}}  \sqrt{R^{2}-(R.sin(\theta))^{2}} \; R.cos(\theta) d\theta\right)$   
$I = \left(\int_{0}^{\frac{\pi}{2}}  \sqrt{R^{2}.(1-sin(\theta)^{2})} \; R.cos(\theta) d\theta\right)$   
$I = R^{2} . \left(\int_{0}^{\frac{\pi}{2}}  \sqrt{1-sin(\theta)^{2}} \; cos(\theta) d\theta\right)$  
         
Or $cos(\theta)^{2}=1-sin(\theta)^{2}$ ainsi :  
$I = R^{2} . \left(\int_{0}^{\frac{\pi}{2}}  cos(\theta)^{2} \;  d\theta\right)$  
  
En utilisant la formule de linérisation [^n1] [^n2].  
$cos(\theta)^{2}=\frac{1+cos(2.\theta)}{2}$  
$I = R^{2} . \left(\int_{0}^{\frac{\pi}{2}}  \frac{1+cos(2.\theta)}{2} \;  d\theta\right)$  
$I = \frac{R^{2}}{2} . \left(\int_{0}^{\frac{\pi}{2}}  1+cos(2.\theta) \;  d\theta\right)$  
  
Une primitive de 1 est donné par $\theta$  
Une primitive de $cos(2.\theta)$ est donné par $\frac{sin(2.\theta)}{2}$  
  
On obtient donc :  
$I = \frac{R^{2}}{2} . [\theta + \frac{sin(2.\theta)}{2}]^{\frac{\pi}{2}}_0$  
$I = \frac{R^{2}}{2} . ((\frac{\pi}{2} + 0)-(0+0)=\frac{R^{2} .\pi}{4})$  
   
On en déduit l'aire d'un cercle qui est 4 fois l'aire du quart de cercle :   
$Aire  = R^{2} .\pi$  

[^n1]: Demonstration formule de linerisation grâce aux formules d'Euler   
$E_{1} : e^{ix}=cos(x)+i.sin(x)$  
$E_{2} : e^{-ix}=cos(x)-i.sin(x)$   
$E_{1} + E_{2} : e^{ix} + e^{-ix} = 2 . cos(x) => cos(x)= \frac{e^{ix} + e^{-ix}}{2}$    
$E_{1} - E_{2} : e^{ix} - e^{-ix} = 2 .i. sin(x) => sin(x)= \frac{e^{ix} - e^{-ix}}{2i}$      
$cos(x)^{2}= \frac{(e^{ix} + e^{-ix})^{2}}{4}$      
$cos(x)^{2}= \frac{cos(2x)+1}{2}$      

[^n2]: Demonstration des formules d'Euler   
Rappelons nous des dérivés $\frac{u}{v}'=\frac{u'v-uv'}{v^{2}}$ et également du fait que si la dérivée d'une fonction $f'$ est nulle sur tout le domaine de définition de $f$ alors la fonction $f$ est constante sur son domaine de définition.  
Posons $f(x)=\frac{cos(x)+isin(x)}{e^{ix}}$  
Calculons sa dérivée $f'(x)= \frac{(-sin(x)+i.cos(x)).e^{ix}-i.e^{ix}.(cos(x)+isin(x))}{(e^{ix})^2}$    
$f'(x)= \frac{-sin(x).e^{ix} + sin(x).e^{ix}+i.e^{ix}.cos(x)-i.e^{ix}.cos(x)}{(e^{ix})^2}$   
$f'(x)= 0$  
Cela implique que la fonction est constante, en valeur $x=0 => f(0)=1$  
Nous avons donc $e^{ix}=cos(x)+i.sin(x)$  